services:
  identity-service:
    build: ./services/identity-service
    container_name: identity-service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - JWT_SECRET=CN4vbU9nRdi1ubOq5a1IYcw5WBvi7FfTz8iqC8ojWGA
      - SUPABASE_URL=https://plruuzubfulccriopggs.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscnV1enViZnVsY2NyaW9wZ2dzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTg0MTA5MSwiZXhwIjoyMDg3NDE3MDkxfQ.hr6sewqiwCtdXTiul3SxkKrwJ33i0BCs4Am7Wrp3siI

  listing-service:
    build: ./services/listing-service
    container_name: listing-service
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - IDENTITY_URL=http://identity-service:8001

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - IDENTITY_URL=http://identity-service:8001

  compliance-service:
    build: ./services/compliance-service
    container_name: compliance-service
    ports:
      - "8004:8004"
    environment:
      - PORT=8004